Update iac.yml

diff --git a/.github/workflows/iac.yml b/.github/workflows/iac.yml
--- a/.github/workflows/iac.yml
+++ b/.github/workflows/iac.yml
@@ -4,9 +4,9 @@ on:
   push:
     branches:
       - iac-eks
-    paths:  
+    paths:
       - github-demo/**
-  workflow_dispatch: 
+  workflow_dispatch:
 
 env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -19,7 +19,7 @@ jobs:
   terraform:
     name: "Deploy Infra with Terraform on AWS"
     runs-on: ubuntu-latest
-    if: github.event_name == 'push'  
+    if: github.event_name == 'push'
     defaults:
       run:
         shell: bash
@@ -29,7 +29,6 @@ jobs:
       - name: Checkout source code
         uses: actions/checkout@v4
 
-      # Configure AWS credentials first to ensure all AWS CLI commands succeed.
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -50,34 +49,37 @@ jobs:
 
       - name: Terraform plan
         id: plan
-        run: terraform plan -no-color -input=true -out planfile
-        continue-on-error: true
+        run: terraform plan -no-color -input=false -out=planfile
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      - name: Show Terraform Plan Output
+        run: terraform show planfile
 
       - name: Terraform apply
         id: apply
-        run: terraform apply -auto-approve -input=true -parallelism=1 planfile
+        run: |
+          if [ -f planfile ]; then
+            terraform apply -auto-approve -input=false -parallelism=1 planfile
+          else
+            echo "Planfile not found. Skipping apply."
+            exit 1
+          fi
 
       - name: List all EKS clusters
         run: aws eks list-clusters --region ${{ env.AWS_REGION }}
 
       - name: Describe the cluster (debug)
         run: |
-         aws eks describe-cluster --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} || echo "Cluster not found!"
-
+          aws eks describe-cluster --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} || echo "Cluster not found!"
 
       - name: Get Kubernetes config
         id: getconfig
         if: steps.apply.outcome == 'success'
-        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} 
+        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
 
       - name: Install Ingress controller
         if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
         run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml
-  
+
   destroy:
     name: "Destroy Infra on AWS"
     runs-on: ubuntu-latest
@@ -104,10 +106,10 @@ jobs:
       - name: Terraform init
         id: init
         run: terraform init -backend-config="bucket=aws-largescaleproject-terraform"
-      
+
       - name: Get Kubernetes config
         id: getconfig
-        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} 
+        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
 
       - name: Delete Ingress controller
         run: kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml
@@ -122,7 +124,7 @@ jobs:
           else
             echo "No images found in $REPOSITORY_NAME."
           fi
-      
+
       - name: Terraform destroy
         id: destroy
         run: terraform destroy -auto-approve -input=false
